### ISSUE TITLE
程序恐慌并表示我不认识 png（vlc的截图）

### ISSUE THREAD

**Issue by madobet** [fantasticmao/moment#6]
```
$ ./moment-2.0-linux -p ./mom
panic: image: unknown format

goroutine 1 [running]:
github.com/FantasticMao/moment/app.Stitch(0xc0000a8340, 0x1, 0x1, 0x78, 0x54470c, 0x1, 0xc0000a8300, 0x0, 0x0)
    /Users/maomao/go/src/github.com/FantasticMao/moment/app/images.go:34 +0xadf
main.main()
    /Users/maomao/go/src/github.com/FantasticMao/moment/main.go:12 +0x93
```
系统 Arch Linux

**Comment by madobet** [comment]
`-p, --path=   The file path of image that need to be stitched`
这个帮助让我以为程序君想要一个文件目录，谁知道他要的是
```
-p a.png -p b.png -p c.png ...
```
我自裁
